apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-che-operator
    app.kubernetes.io/part-of: devworkspace-che-operator
  name: devworkspace-che-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
