operator-path: ../../deploy/k8s/controller.yaml
role-paths:
  - "generated/roles/role.yaml"
  - "generated/roles/edit-workspaces-cluster-role.yaml"
crd-cr-paths:
  - "../../deploy/crds/workspace.che.eclipse.org_components_crd.yaml"
  - "../../deploy/crds/workspace.che.eclipse.org_workspaceroutings_crd.yaml"
  - "../../deploy/crds/workspace.che.eclipse.org_workspaces_crd.yaml"
