apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-che-operator
    app.kubernetes.io/part-of: devworkspace-che-operator
  name: devworkspace-che-serviceaccount
  namespace: devworkspace-che
