apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |
      ---
      apiVersion: workspace.che.eclipse.org/v1alpha1
      kind: Workspace
      metadata:
        name: python-sample
      spec:
        started: true
        devfile:
          apiVersion: 1.0.0
          metadata:
            name: wksp-4xzm
          projects: []
          components:
            - alias: theia-ide
              type: cheEditor
              id: eclipse/che-theia/latest
            - type: chePlugin
              id: eclipse/che-machine-exec-plugin/latest
            - type: chePlugin
              id: ms-python/python/latest
              memoryLimit: 512Mi
          commands: []
        ...
    capabilities: Basic Install
  name: eclipse-che-preview-openshift.v9.9.9-nightly.1589335392
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Component
      name: components.workspace.che.eclipse.org
      version: v1alpha1
      displayName: Component CRD
      description: The CRD of a Component
    - kind: WorkspaceRouting
      name: workspaceroutings.workspace.che.eclipse.org
      version: v1alpha1
      displayName: WorkspaceRouting CRD
      description: The CRD of a WorkspaceRoute
    - kind: Workspace
      name: workspaces.workspace.che.eclipse.org
      version: v1alpha1
      displayName: Workspace CRD
      description: The CRD of a Workspace
  description: Placeholder description
  displayName: Eclipse Che Preview Openshift
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - watch
          - list
          - get
          - create
          - update
          - patch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          verbs:
          - watch
          - list
          - get
          - create
          - update
        - apiGroups:
          - ""
          - route.openshift.io
          resources:
          - routes/status
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - list
          - get
          - watch
        - apiGroups:
          - apps
          - extensions
          resources:
          - deployments
          - replicasets
          verbs:
          - '*'
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - ""
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - che-workspace-controller
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - workspace.che.eclipse.org
          resources:
          - '*'
          - workspaceroutings
          verbs:
          - '*'
        - apiGroups:
          - ""
          - route.openshift.io
          resources:
          - routes/custom-host
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - create
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - '*'
        - apiGroups:
          - oauth.openshift.io
          resources:
          - oauthclients
          verbs:
          - create
          - get
          - delete
          - list
          - patch
          - update
          - watch
          - deletecollection
        serviceAccountName: che-workspace-controller
      - rules:
        - apiGroups:
          - workspace.che.eclipse.org
          resources:
          - workspaces
          - workspaceroutings
          - components
          verbs:
          - create
          - delete
          - deletecollection
          - patch
          - update
        serviceAccountName: edit-workspaces
      deployments:
      - name: che-workspace-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: che-workspace-controller
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/restartedAt: ""
              labels:
                app: che-workspace-controller
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: che-workspace-operator
                image: quay.io/che-incubator/che-workspace-controller:nightly
                imagePullPolicy: Always
                name: che-workspace-controller
                # ports:
                # - containerPort: 8443
                #   name: webhook-server
                resources: {}
                # volumeMounts:
                # - mountPath: /tmp/k8s-webhook-server/serving-certs
                #   name: webhook-tls-certs
                #   readOnly: true
              serviceAccountName: che-workspace-controller
              # volumes:
              # - name: webhook-tls-certs
              #   projected:
              #     sources:
              #     - configMap:
              #         items:
              #         - key: service-ca.crt
              #           path: ./ca.crt
              #         name: che-workspace-controller-secure-service
              #     - secret:
              #         name: workspace-controller
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 9.9.9-nightly.1589335392
